name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

jobs:
  coding_style_check:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: coding style
        run: check.sh $(pwd) $(pwd)

      - name: Create annotation for coding-style errors
        run:  |
          STYLE_ERROR=$(cat $(pwd)/coding-style-reports.log)
          for ERRORS in $STYLE_ERROR; do
            array=(`echo $ERRORS | sed 's/:/\n/g'`)
            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
          done

      - name: Report style
        run: |
          STYLE_ERROR=$(cat /tmp/coding-style-reports.log | wc -l)
          if [ $STYLE_ERROR -gt 0 ]; then
            exit 1
          fi

  checking_compilation:
    runs-on: ubuntu-latest
    needs: coding_style_check
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: compilation
        run: make

      - name: compilation
        run: make clean

      - name: file exist
        run: |
          OIFS=$IFS
          IFS=','
          for x in $EXECUTABLES
            do
              ./$x $ARGUMENTS
            done
          IFS=$OIFS

  run_tests:
    runs-on: ubuntu-latest
    needs: checking_compilation
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: compile_tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
